# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Leonardo2718
email: leonardo2718@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Leonardo Banderali's personal website. Find his blog posts and other information here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Leonardo2718
linkedin_username: leonardo2718

# Build settings
markdown: kramdown
theme: minima
plugins:
   - jekyll-paginate-v2
#  - jekyll-feed

minima:
    date_format: "%Y-%m-%d"

pagination:
    enabled: true
    per_page: 5
    #permalink: '/page/:num/'
    #title: ' - page :num'
    #limit: 0
    #sort_field: 'date'
    #sort_reverse: true

autopages:
    enabled: true
    categories:
        layouts:
            - 'category-page.html'
        title: ':cat'
        permalink: '/category/:cat-:num'
    collections:
        enabled: false
    tags:
        enabled: false

show_excerpts: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
